<?php
  if(!isset($_COOKIE['level'])){
    setcookie('level','2',0,'/');
  }
  setcookie('active','2',0,'/');
?>

<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <link rel="stylesheet" href="../css/index.css">
    <link rel="stylesheet" href="../css/accordion.css">
    <link rel="shortcut icon" href="../images/favicon/favicon.ico">
    <title>稲岸の部屋</title>
  </head>
  <body>
    <div class="container">
      <div class="title-wrapper">
        <span class="room">3年3組</span>
        <div class="title">
        </div>
      </div>
      <div class="wrapper">
        <?php include("../common/sidebarall.php") ?>
        <div class="content">
          <nav>
            <ol class="breadcrumb">
              <li><a href="/">ホーム</a></li>
              <li><a href="keyword2.php">ミッション２</a></li>
              <li>8/13 嬉しい連絡</li>
            </ol>
          </nav>
          <h2 class="blogtitle">嬉しい連絡</h2>
          <div class="main">
            <p>実は今日、友達から嬉しい連絡があってさ、、、</p>

            <p>このブログをもしまだやっていたら久々に読んでみたいからリンクを送ってほしいってやつが現れたんだよ！</p>

            <p>
              このブログを覚えていてくれた人がいるのはとても嬉しいことだ。
              でももう中学のころのページはすべて撤去しちゃったけどな
              身内ノリが激しすぎてとてもじゃないけど見てられなかったんだよな、、、
              あの頃は、そういうのが楽しかったんだけどな。
            </p>

            <p>中学時代に書いた日記なんてとても他人には見せられないとんでもない代物だろ？
              日記を書いたことがあるやつなら分かってくれると思う。</p>



            <div class="kyounazo">
              <h2 class="nazotitle2">今日の一枚</h2>
              <!-- Image Map Generated by http://www.image-map.net/ -->
              <img src="../images/nazo13.png" usemap="#image-map" class="nazo">

              <map name="image-map">
                  <area target="" alt="" title="" href="../secret/test.php" coords="104,78,57" shape="circle">
              </map>
            </div>
          </div>
          <div class="date">2022/08/13</div>
          <?php include('../common/comment.php') ?>
        </div>  
      </div>
    </div>
    <?php include("../common/footer.php") ?>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="../javascript/jquery.rwdImageMaps.js"></script>
    <script>
      jQuery( 'img[usemap]' ).rwdImageMaps();
    </script>
    <script src="../javascript/accordion.js"></script>  
  </body>
</html>